apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: kubernetes-publicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: jcnazate/auth-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/autentificacion_db"  # Cambiado para usar PostgreSQL
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"  # Usuario de PostgreSQL
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"  # Contraseña de PostgreSQL
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: kubernetes-publicaciones
spec:
  selector:
    app: auth-service
  ports:
    - port: 80
      targetPort: 8083
      nodePort: 30081
  type: NodePort