apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-publicaciones
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kubernetes-publicaciones
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: kubernetes-publicaciones
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Ajusta el tamaño del almacenamiento según tus necesidades
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: kubernetes-publicaciones
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13  # Puedes usar la versión de PostgreSQL que prefieras
          env:
            - name: POSTGRES_USER
              value: "admin"  # Nombre de usuario por defecto
            - name: POSTGRES_PASSWORD
              value: "password"  # Contraseña del usuario
            - name: POSTGRES_DB
              value: "mydb"  # Nombre de la base de datos
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
