apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicaciones
  namespace: kubernetes-publicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publicaciones
  template:
    metadata:
      labels:
        app: publicaciones
    spec:
      containers:
        - name: publicaciones
          image: jcnazate/publicaciones
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cockroachdb-public:26257/publicaciones_db?sslmode=disable"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""  # Asegúrate de que CockroachDB acepte esto o añade la contraseña
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "admin"  # O "admin" si cambiaste las credenciales
            - name: SPRING_RABBITMQ_PASSWORD
              value: "admin"  # O la contraseña de "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: publicaciones
  namespace: kubernetes-publicaciones
spec:
  selector:
    app: publicaciones
  ports:
    - port: 80
      targetPort: 8084
      nodePort: 30085
  type: NodePort